<?php 

return array (
  0 => 
  array (
    'id' => '4938',
    'type' => 'variable',
    'product_url' => NULL,
    'name' => 'Greca Odissea Sneakers uomo Versace bianche',
    'slug' => 'greca-odissea-sneakers-uomo-versace-bianche',
    'status' => 'publish',
    'featured' => false,
    'catalog_visibility' => 'visible',
    'description' => 'Queste leggere sneakers Odissea, con motivo Greca cucito sui lati, sono dotate di dinamiche suole in gomma per assorbire l\'impatto e creare un look deciso. Il modello è impreziosito dal logo inciso sul tallone.

-Motivo Greca
-Lacci
-Modello basso
-Logo applicato sulla linguetta
-Composizione esterno: 100% pelle di vitello
-Fodera 1: 80% nylon, 20% elastan
-Fodera 2: 100% pelle di vitello
-Suola: 100% gomma

Per istruzioni di lavaggio e cura, consigliamo di leggere attentamente l\'etichetta del prodotto presente all\'interno del capo. Per domande o dubbi, contattaci o rivolgersi a un servizio di lavanderia qualificato per la pulizia del capo.',
    'short_description' => '',
    'sku' => '',
    'date_created' => '2023-10-21 18:20:28',
    'date_modified' => '2023-12-02 00:08:23',
    'price' => '79.90',
    'regular_price' => '',
    'sale_price' => '',
    'manage_stock' => false,
    'stock_quantity' => NULL,
    'stock_status' => 'instock',
    'is_sold_individually' => false,
    'weight' => '',
    'length' => '',
    'width' => '',
    'height' => '',
    'parent_id' => 0,
    'tags' => 
    array (
    ),
    'categories' => 
    array (
    ),
    'image_id' => '4943',
    'image' => 
    array (
      0 => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png',
      1 => 1024,
      2 => 1024,
      3 => true,
    ),
    'gallery_image_ids' => 
    array (
      0 => 4942,
      1 => 4941,
      2 => 4940,
      3 => 4939,
      4 => 4944,
    ),
    'gallery_images' => 
    array (
      0 => 
      array (
        0 => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-4-1024x1024.png',
        1 => 1024,
        2 => 1024,
        3 => true,
      ),
      1 => 
      array (
        0 => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-3-1024x1024.png',
        1 => 1024,
        2 => 1024,
        3 => true,
      ),
      2 => 
      array (
        0 => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-2-1024x1024.png',
        1 => 1024,
        2 => 1024,
        3 => true,
      ),
      3 => 
      array (
        0 => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-1-1024x1024.png',
        1 => 1024,
        2 => 1024,
        3 => true,
      ),
      4 => 
      array (
        0 => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-6-1024x1024.png',
        1 => 1024,
        2 => 1024,
        3 => true,
      ),
    ),
    'attributes' => 
    array (
      'pa_taglia' => 
      array (
        'term_names' => 
        array (
          0 => '38',
          1 => '38-5',
          2 => '39',
          3 => '39-5',
          4 => '40',
          5 => '40-5',
          6 => '41',
          7 => '41-5',
          8 => '42',
          9 => '42-5',
          10 => '43',
          11 => '43-5',
          12 => '44',
          13 => '44-5',
          14 => '45',
          15 => '45-5',
          16 => '46',
          17 => '46-5',
          18 => '47',
          19 => '47-5',
          20 => '',
        ),
        'is_visible' => true,
      ),
    ),
    'variations' => 
    array (
      0 =>   /* variation_id = 6173 */
      array (
        'attributes' => 
        array (        // por que no recupera los atributos??/
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6173,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      1 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6174,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      2 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6175,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      3 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6176,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      4 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6177,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      5 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6178,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      6 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6179,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      7 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6180,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      8 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6181,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      9 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6182,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      10 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6183,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      11 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6184,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      12 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6185,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      13 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6186,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      14 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6187,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      15 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6188,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      16 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6189,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      17 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6190,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      18 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6191,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      19 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 6192,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
      20 => 
      array (
        'attributes' => 
        array (
        ),
        'availability_html' => '',
        'backorders_allowed' => false,
        'dimensions' => 
        array (
          'length' => '',
          'width' => '',
          'height' => '',
        ),
        'dimensions_html' => 'N/A',
        'display_price' => 79.9,
        'display_regular_price' => 79.9,
        'image' => 
        array (
          'title' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'caption' => '',
          'url' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'alt' => 'Greca-Odissea-Sneakers-Versace-bianco-5',
          'src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png',
          'srcset' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-600x600.png 600w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png 300w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png 100w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-1024x1024.png 1024w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-150x150.png 150w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-768x768.png 768w, http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png 1080w',
          'sizes' => '(max-width: 600px) 100vw, 600px',
          'full_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5.png',
          'full_src_w' => 1080,
          'full_src_h' => 1080,
          'gallery_thumbnail_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-100x100.png',
          'gallery_thumbnail_src_w' => 100,
          'gallery_thumbnail_src_h' => 100,
          'thumb_src' => 'http://luxuritop.test/wp-content/uploads/2023/10/Greca-Odissea-Sneakers-Versace-bianco-5-300x300.png',
          'thumb_src_w' => 300,
          'thumb_src_h' => 300,
          'src_w' => 600,
          'src_h' => 600,
        ),
        'image_id' => 4943,
        'is_downloadable' => false,
        'is_in_stock' => true,
        'is_purchasable' => true,
        'is_sold_individually' => 'no',
        'is_virtual' => false,
        'max_qty' => '',
        'min_qty' => 1,
        'price_html' => '',
        'sku' => '',
        'variation_description' => '',
        'variation_id' => 4946,
        'variation_is_active' => true,
        'variation_is_visible' => true,
        'weight' => '',
        'weight_html' => 'N/A',
      ),
    ),
  ),
);